version: "3.7"
services:
  lic:
    build: .
    container_name: trs
    tty: true
    restart: always
    ports:
      - "10003:8081"
    environment:
      - "GZCTF_FLAG=NepCTF{testflag-test-test-test-TEST}"